### ISSUE TITLE
是否用了mobx就可以基本或者彻底抛弃state了？

### ISSUE THREAD

**Issue by lsamio** [dabit3/react-native-mobx-list-app#1]
刚开始踩坑。。。在某些博客上看到用了mobx就可以彻底抛弃state了，但我看到你的代码里大量使用state，不知道是不是这样。。

**Comment by dustturtle** [comment]
@lsamio 对于这个问题你有答案了吗，朋友

**Comment by dustturtle** [comment]
我的理解是可以在很多场景下少使用state了
